### ISSUE TITLE
建议可以去研究学习下chatGPT，学而思为了服务大家，给大家更好的原生的编程体验，如果大家不保护，我感觉后面会限制越来越多，大家用着就不方便了。

### ISSUE THREAD

**Issue by linfeng1-tal** [FurryR/XesExt#4]
建议可以去研究学习下chatGPT，学而思为了服务我们小朋友，给大家更好的原生的编程体验，如果大家不保护，我感觉后面会限制越来越多，大家用着就不方便了。

**Comment by FurryR** [comment]
这下有 ChatGPT 了。
https://greasyfork.org/zh-CN/scripts/502832-xueersi-aurora
